app = "telegraminsurancebot"
primary_region = "ams"

[build]
  image = "mcr.microsoft.com/dotnet/aspnet:8.0"

[env]
  DOTNET_RUNNING_IN_CONTAINER = "true"

[processes]
  app = "dotnet TelegramInsuranceBot.ConsoleApp.dll"
